language: r
cache: packages
os: linux

addons:
  apt:
    packages:
    - libssh-dev
    - libapparmor-dev

matrix:
  include:
    - r: release
      env: R_CODECOV=true
    - r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

r_binary_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
